repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  createNamespace: true

releases:
  - name: prepper-postgres
    namespace: {{ env "NAMESPACE" | default "prepper" }}
    chart: bitnami/postgresql
    version: "~18.0"
    values:
      - deploy/values/postgres.yaml

  - name: prepper-backend
    namespace: {{ env "NAMESPACE" | default "prepper" }}
    chart: ./app/helm
    needs:
      - {{ env "NAMESPACE" | default "prepper" }}/prepper-postgres
    values:
      - deploy/values/backend.yaml
